### ISSUE TITLE
[BUG] Raw text is displayed inside list items

### ISSUE THREAD

**Issue by amokmen** [spenserblack/steamdown#127]
Input:
```
* [URL](https://google.com)
```

Output:
```
[list]
    [*][URL](https://google.com)
[/list]
```

Should be:
```
[list]
    [*] [url=https://google.com]URL[/url]
[/list]
```

**Comment by spenserblack** [comment]
Thanks for the report!

I'll need to investigate, but this may be an upstream issue. [Marked.js passes text to the renderer extension](https://marked.js.org/using_pro#renderer), which should already be parsed, similar to how `heading(_: string)` works. In fact, all inline text (`*emphasis*`, `__underline__`, etc.) seems to be unparsed in list items.

**Comment by spenserblack** [comment]
Sorry for the wait! If you installed via npm, 0.2.1 was just released. Otherwise, you can use the web editor.

**Comment by amokmen** [comment]
>Sorry for the wait!

No worries, thank you very much!
Just tested, seems OK.
