### ISSUE TITLE
Underlines break nested inline syntax

### ISSUE THREAD

**Issue by ilyvion** [spenserblack/steamdown#224]
If you write `***t***`, you get `[i][b]t[/b][/i]`, if you write `__t__`, you get `[u]t[/u]`, but if you write `***__t__***`, you get `[i][b]__t__[/b][/i]` and if you write `__***t***__` you get `[u]***t***[/u]`. In both cases, I'd expect all three of `[i]`, `[b]` and `[u]` to be present, not just whichever is outermost.

**Comment by spenserblack** [comment]
Oof, thanks for the report. I'm currently focusing on writing my own parser instead of using marked.js and extending/overriding its behavior. Once that custom parser is done this should be fixed.

**Comment by spenserblack** [comment]
Sorry for the wait! I'm nearing the finish line for the rewrite :checkered_flag: 
I believe that I've fixed this issue (at the expense of creating #233 :cry:)

How did you use this? Did you use the site or the CLI? I haven't published the newest version yet, but if you're up for it you can clone this project and try out the CLI.

**Comment by ilyvion** [comment]
I've used it in both ways, so I could test the CLI, but also I trust that your own testing is decent enough. 😅

In fact, I only discovered this issue because someone else that I directed to this tool pointed it out to me, lol.

**Comment by spenserblack** [comment]
> but also I trust that your own testing is decent enough.

Thanks! While I'm confident with my test cases, just an FYI that community-provided test cases are always welcome (I'll add this note to `CONTRIBUTING.md` when I get around to writing one).
